// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkkHVBEELUozfJFAPG6aJ-ldXQNNV57ZU',
    appId: '1:1078875729528:web:0606d8c865dba98033878d',
    messagingSenderId: '1078875729528',
    projectId: 'lanka-xplore',
    authDomain: 'lanka-xplore.firebaseapp.com',
    storageBucket: 'lanka-xplore.firebasestorage.app',
    measurementId: 'G-33XN4E688E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLM-10dZdGsB-2F_TuCjNqbWQbrDkI0QI',
    appId: '1:1078875729528:android:ec65efecd6c1167e33878d',
    messagingSenderId: '1078875729528',
    projectId: 'lanka-xplore',
    storageBucket: 'lanka-xplore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu4_B0ZDCROPlR46-KSYat7TQkSIRL6dc',
    appId: '1:1078875729528:ios:3fd4fd1755517fcb33878d',
    messagingSenderId: '1078875729528',
    projectId: 'lanka-xplore',
    storageBucket: 'lanka-xplore.firebasestorage.app',
    iosBundleId: 'com.example.lankaXplore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu4_B0ZDCROPlR46-KSYat7TQkSIRL6dc',
    appId: '1:1078875729528:ios:3fd4fd1755517fcb33878d',
    messagingSenderId: '1078875729528',
    projectId: 'lanka-xplore',
    storageBucket: 'lanka-xplore.firebasestorage.app',
    iosBundleId: 'com.example.lankaXplore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkkHVBEELUozfJFAPG6aJ-ldXQNNV57ZU',
    appId: '1:1078875729528:web:97d0fc55bac4fb4f33878d',
    messagingSenderId: '1078875729528',
    projectId: 'lanka-xplore',
    authDomain: 'lanka-xplore.firebaseapp.com',
    storageBucket: 'lanka-xplore.firebasestorage.app',
    measurementId: 'G-CYS4LTQCVP',
  );
}
